# Generated by Django 4.1.4 on 2023-01-25 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioLabels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('dataset', models.CharField(blank=True, max_length=255)),
                ('updatedate', models.DateTimeField(default=django.utils.timezone.now)),
                ('labeluser', models.CharField(default='System', max_length=255)),
            ],
        ),
    ]
