# Generated by Django 4.1.4 on 2023-01-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiolabels',
            name='labelregions',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
