# Generated by Django 4.1.4 on 2023-01-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_audiolabels_labelusername'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('progress', models.FloatField(default=0)),
                ('progressname', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
