# Generated by Django 4.1.4 on 2023-01-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_taskprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiolabels',
            name='lowquality',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiolabels',
            name='unclear',
            field=models.BooleanField(default=False),
        ),
    ]
