# Generated by Django 4.1.4 on 2023-09-08 19:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_classifierresults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifierresults',
            name='updatedate',
        ),
        migrations.AddField(
            model_name='classifierresults',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classifierresults',
            name='data_json',
            field=models.JSONField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classifierresults',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='classifierresults',
            name='data',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='TrainingTasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complete', models.BooleanField(default=False)),
                ('config', models.TextField()),
                ('config_json', models.JSONField()),
                ('priority', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('result_data', models.JSONField(blank=True)),
                ('classifier_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_tasks', to='app.classifierresults')),
            ],
        ),
    ]
