# Generated by Django 4.1.4 on 2023-09-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_classifierresults_updatedate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetPicklesStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.TextField()),
                ('stats', models.TextField()),
                ('stats_json', models.JSONField()),
            ],
        ),
    ]
